title: PIXEL
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /images/imda-logo.png

# Site colors
colors:
  primary-color: '#702f8a'
  secondary-color: '#40c1ac'
  media-colors:
    - title: media-color-one
      color: '#47bbe9'
    - title: media-color-two
      color: '#f18aa2'
    - title: media-color-three
      color: '#43bcac'
    - title: media-color-four
      color: '#47bbe9'
    - title: media-color-five
      color: '#fac54c'
    - title: media-color-six
      color: '#eb4034'
    - title: media-color-seven
      color: '#eb12ff'  


collections:
  about:
    output: true
  community:
    output: true
resources_name: events
future: true
google_analytics: UA-79861556-1

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test

